// Code generated by sqlc. DO NOT EDIT.

package goServer

import (
	"encoding/json"
)

type Launchpad struct {
	ID               int64           `json:"id"`
	HashValue        string          `json:"hash_value"`
	FirstOwnerEmail  string          `json:"first_owner_email"`
	CaAddress        string          `json:"ca_address"`
	ChainID          string          `json:"chain_id"`
	Price            int32           `json:"price"`
	AirdropAddress   json.RawMessage `json:"airdrop_address"`
	WhitelistAddress json.RawMessage `json:"whitelist_address"`
	CreatedAt        string          `json:"created_at"`
}
